language: node_js
node_js: 
  - "stable"
services:
  - postgresql
before_script:
  - psql -c 'create database ireportertest_db;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

cache:
  directories:
    - "node_modules"
after_success: -npm run coverage